### ISSUE TITLE
IM LAZY ... WHY IS IMAP / POP OR EVEN GMAIL ?

### ISSUE THREAD

**Issue by RicePudding0xL** [forentfraps/discord-twitch-points-farm#1]
IM LAZY ... WHY IS IMAP / POP OR EVEN GMAIL ? HOW IS IT DIFFERENT IN FUNCTIONALITY FROM TKD-ALEX THAT IT REQUIRES IMAP ENABLED MAILS?

**Comment by forentfraps** [comment]
i wanted to automate email code verification for twitch accounts
Its pretty tedious to get the code for every account

**Comment by forentfraps** [comment]
There is not much difference with the twitch bot itself. Its just that i did not find a good way to do it for multiple accounts. Also i made discord logging which is neat when used on external server

**Comment by forentfraps** [comment]
> IM LAZY ... WHY IS IMAP / POP OR EVEN GMAIL ? HOW IS IT DIFFERENT IN FUNCTIONALITY FROM TKD-ALEX THAT IT REQUIRES IMAP ENABLED MAILS?

About Gmail: i made it for easier setup, because it is tedious to work with multiple accounts with email linked to.
I could make it other for other mails.
Difference in functionality: semi-automated cookies grabber, better support for multiple accounts, discord bot integration
